services:

  postgres:
    image: postgres:18
    container_name: postgres-projeto

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    build: .
    image: projeto1-backend
    container_name: projeto1-backend

    depends_on:
      postgres:
        condition: service_healthy

    env_file:
      - .env

    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      DATASOURCE_USERNAME: ${POSTGRES_USER}
      DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "8080:8080"


  frontend:
    build:
      context: ../projeto1-frontend
      args:
        VITE_API_URL: ${VITE_API_URL}

    image: projeto1-frontend
    container_name: projeto1-frontend

    depends_on:
      - backend

    ports:
      - "5173:80"


volumes:
  postgres_data: