-- Os dados existentes são exclusivamente de desenvolvimento. A limpeza permite
-- chegar ao novo modelo sem inventar credenciais ou papéis para pessoas legadas.
TRUNCATE TABLE
    tb_evidencias_movimentacao,
    tb_comprovantes_movimentacao,
    tb_movimentacoes,
    tb_itens_nota_fiscal,
    tb_notas_fiscais,
    tb_materiais,
    tb_contratos,
    tb_funcionarios,
    tb_usuarios
RESTART IDENTITY CASCADE;

DROP TRIGGER IF EXISTS trg_bloquear_alteracao_movimentacao_finalizada ON tb_movimentacoes;
DROP TRIGGER IF EXISTS trg_validar_movimentacao_estorno ON tb_movimentacoes;

ALTER TABLE tb_usuarios
    ADD COLUMN nome VARCHAR(150) NOT NULL,
    ADD COLUMN cpf VARCHAR(11) NOT NULL,
    ADD COLUMN celular VARCHAR(20) NOT NULL;

ALTER TABLE tb_usuarios DROP CONSTRAINT ck_usuarios_role;
ALTER TABLE tb_usuarios
    ADD CONSTRAINT ck_usuarios_role
        CHECK (role IN ('ADMIN', 'OPERADOR', 'GERENTE', 'ENCARREGADO')),
    ADD CONSTRAINT ck_usuarios_nome_nao_vazio CHECK (BTRIM(nome) <> ''),
    ADD CONSTRAINT ck_usuarios_celular_nao_vazio CHECK (BTRIM(celular) <> ''),
    ADD CONSTRAINT ck_usuarios_cpf_11_digitos CHECK (cpf ~ '^[0-9]{11}$');

CREATE UNIQUE INDEX uk_usuarios_cpf_normalizado
    ON tb_usuarios (REGEXP_REPLACE(cpf, '[^0-9]', '', 'g'));

ALTER TABLE tb_movimentacoes
    DROP CONSTRAINT fk_movimentacoes_funcionario;
DROP INDEX idx_movimentacoes_funcionario;
ALTER TABLE tb_movimentacoes RENAME COLUMN funcionario_id TO encarregado_id;
ALTER TABLE tb_movimentacoes
    ADD CONSTRAINT fk_movimentacoes_encarregado
        FOREIGN KEY (encarregado_id) REFERENCES tb_usuarios(id);
CREATE INDEX idx_movimentacoes_encarregado ON tb_movimentacoes(encarregado_id);

CREATE TABLE tb_requisicoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(4000) NOT NULL,
    gerente_id BIGINT NOT NULL,
    encarregado_id BIGINT NOT NULL,
    contrato_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    criado_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    confirmado_em TIMESTAMP(6) WITHOUT TIME ZONE,
    confirmado_por_id BIGINT,
    versao BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_requisicoes_gerente FOREIGN KEY (gerente_id) REFERENCES tb_usuarios(id),
    CONSTRAINT fk_requisicoes_encarregado FOREIGN KEY (encarregado_id) REFERENCES tb_usuarios(id),
    CONSTRAINT fk_requisicoes_contrato FOREIGN KEY (contrato_id) REFERENCES tb_contratos(id),
    CONSTRAINT fk_requisicoes_confirmado_por FOREIGN KEY (confirmado_por_id) REFERENCES tb_usuarios(id),
    CONSTRAINT ck_requisicoes_descricao_nao_vazia CHECK (BTRIM(descricao) <> ''),
    CONSTRAINT ck_requisicoes_status CHECK (
        status IN ('PENDENTE', 'AGUARDANDO_CONFIRMACAO', 'CONCLUIDA')
    ),
    CONSTRAINT ck_requisicoes_confirmacao CHECK (
        (status = 'CONCLUIDA' AND confirmado_em IS NOT NULL AND confirmado_por_id IS NOT NULL)
        OR
        (status <> 'CONCLUIDA' AND confirmado_em IS NULL AND confirmado_por_id IS NULL)
    )
);

CREATE INDEX idx_requisicoes_gerente ON tb_requisicoes(gerente_id);
CREATE INDEX idx_requisicoes_encarregado ON tb_requisicoes(encarregado_id);
CREATE INDEX idx_requisicoes_contrato ON tb_requisicoes(contrato_id);
CREATE INDEX idx_requisicoes_status ON tb_requisicoes(status);

ALTER TABLE tb_movimentacoes ADD COLUMN requisicao_id BIGINT;
ALTER TABLE tb_movimentacoes
    ADD CONSTRAINT fk_movimentacoes_requisicao
        FOREIGN KEY (requisicao_id) REFERENCES tb_requisicoes(id),
    ADD CONSTRAINT ck_movimentacoes_contexto_operacional CHECK (
        (tipo = 'ENTRADA'
            AND encarregado_id IS NULL
            AND contrato_id IS NULL
            AND requisicao_id IS NULL)
        OR
        (tipo IN ('RETIRADA', 'DEVOLUCAO', 'ESTORNO_RETIRADA', 'ESTORNO_DEVOLUCAO')
            AND encarregado_id IS NOT NULL
            AND contrato_id IS NOT NULL
            AND (requisicao_id IS NULL OR tipo IN ('RETIRADA', 'ESTORNO_RETIRADA')))
    );
CREATE INDEX idx_movimentacoes_requisicao ON tb_movimentacoes(requisicao_id);

ALTER TABLE tb_comprovantes_movimentacao
    RENAME COLUMN funcionario_id TO encarregado_id;
ALTER TABLE tb_comprovantes_movimentacao
    RENAME COLUMN funcionario_nome TO encarregado_nome;
ALTER TABLE tb_comprovantes_movimentacao
    RENAME COLUMN funcionario_cargo TO encarregado_cpf;
ALTER TABLE tb_comprovantes_movimentacao
    ALTER COLUMN encarregado_cpf TYPE VARCHAR(11),
    ADD COLUMN requisicao_id BIGINT,
    ADD COLUMN requisicao_descricao VARCHAR(4000);

ALTER TABLE tb_evidencias_movimentacao
    RENAME COLUMN funcionario_id TO encarregado_id;
ALTER TABLE tb_evidencias_movimentacao
    RENAME COLUMN funcionario_nome TO encarregado_nome;
ALTER TABLE tb_evidencias_movimentacao
    ADD COLUMN assinante_id BIGINT,
    ADD COLUMN assinante_nome VARCHAR(150),
    ADD COLUMN assinante_username VARCHAR(100),
    ADD CONSTRAINT ck_evidencias_assinante CHECK (
        (tipo = 'ASSINATURA' AND assinante_id IS NOT NULL AND assinante_nome IS NOT NULL)
        OR tipo = 'FOTO_DEVOLUCAO'
    );

DROP TABLE tb_funcionarios;

CREATE OR REPLACE FUNCTION fn_validar_movimentacao_estorno()
RETURNS TRIGGER AS $$
DECLARE
    origem tb_movimentacoes%ROWTYPE;
BEGIN
    IF NEW.tipo IN ('ESTORNO_RETIRADA', 'ESTORNO_DEVOLUCAO') THEN
        SELECT * INTO origem FROM tb_movimentacoes WHERE id = NEW.movimentacao_origem_id;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'Movimentação de origem do estorno não encontrada'
                USING ERRCODE = '23503';
        END IF;
        IF (NEW.tipo = 'ESTORNO_RETIRADA' AND origem.tipo <> 'RETIRADA')
            OR (NEW.tipo = 'ESTORNO_DEVOLUCAO' AND origem.tipo <> 'DEVOLUCAO')
            OR NEW.quantidade IS DISTINCT FROM origem.quantidade
            OR NEW.material_id IS DISTINCT FROM origem.material_id
            OR NEW.encarregado_id IS DISTINCT FROM origem.encarregado_id
            OR NEW.contrato_id IS DISTINCT FROM origem.contrato_id
            OR NEW.requisicao_id IS DISTINCT FROM origem.requisicao_id
            OR NEW.nota_fiscal_id IS NOT NULL THEN
            RAISE EXCEPTION 'O estorno deve reproduzir integralmente os dados da movimentação de origem'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_validar_movimentacao_estorno
BEFORE INSERT ON tb_movimentacoes
FOR EACH ROW EXECUTE FUNCTION fn_validar_movimentacao_estorno();

CREATE OR REPLACE FUNCTION fn_bloquear_alteracao_movimentacao_finalizada()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Movimentações finalizadas não podem ser excluídas'
            USING ERRCODE = '55000';
    END IF;
    IF OLD.data_finalizacao IS NOT NULL AND (
        OLD.encarregado_id IS DISTINCT FROM NEW.encarregado_id
        OR OLD.contrato_id IS DISTINCT FROM NEW.contrato_id
        OR OLD.material_id IS DISTINCT FROM NEW.material_id
        OR OLD.quantidade IS DISTINCT FROM NEW.quantidade
        OR OLD.tipo IS DISTINCT FROM NEW.tipo
        OR OLD.data_movimentacao IS DISTINCT FROM NEW.data_movimentacao
        OR OLD.data_finalizacao IS DISTINCT FROM NEW.data_finalizacao
        OR OLD.usuario_id IS DISTINCT FROM NEW.usuario_id
        OR OLD.nota_fiscal_id IS DISTINCT FROM NEW.nota_fiscal_id
        OR OLD.observacao IS DISTINCT FROM NEW.observacao
        OR OLD.idempotency_key IS DISTINCT FROM NEW.idempotency_key
        OR OLD.request_fingerprint IS DISTINCT FROM NEW.request_fingerprint
        OR OLD.movimentacao_origem_id IS DISTINCT FROM NEW.movimentacao_origem_id
        OR OLD.requisicao_id IS DISTINCT FROM NEW.requisicao_id
    ) THEN
        RAISE EXCEPTION 'Dados críticos de uma movimentação finalizada não podem ser alterados'
            USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_bloquear_alteracao_movimentacao_finalizada
BEFORE UPDATE OR DELETE ON tb_movimentacoes
FOR EACH ROW EXECUTE FUNCTION fn_bloquear_alteracao_movimentacao_finalizada();
