CREATE TABLE tb_requisicoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gerente_solicitante_id BIGINT NOT NULL,
    encarregado_destinatario_id BIGINT NOT NULL,
    contrato_id BIGINT NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    observacao VARCHAR(1000),
    status VARCHAR(20) NOT NULL,
    criada_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    visualizada_em TIMESTAMP(6) WITHOUT TIME ZONE,
    concluida_em TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT ck_requisicoes_tipo CHECK (tipo IN ('RETIRADA', 'DEVOLUCAO')),
    CONSTRAINT ck_requisicoes_status CHECK (status IN ('PENDENTE', 'VISUALIZADA', 'CONCLUIDA', 'CANCELADA')),
    CONSTRAINT fk_requisicoes_gerente FOREIGN KEY (gerente_solicitante_id) REFERENCES tb_usuarios(id),
    CONSTRAINT fk_requisicoes_encarregado FOREIGN KEY (encarregado_destinatario_id) REFERENCES tb_usuarios(id),
    CONSTRAINT fk_requisicoes_contrato FOREIGN KEY (contrato_id) REFERENCES tb_contratos(id)
);

CREATE TABLE tb_requisicao_itens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requisicao_id BIGINT NOT NULL,
    material_id BIGINT NOT NULL,
    quantidade INTEGER NOT NULL,
    CONSTRAINT ck_requisicao_itens_quantidade CHECK (quantidade > 0),
    CONSTRAINT uk_requisicao_itens_material UNIQUE (requisicao_id, material_id),
    CONSTRAINT fk_requisicao_itens_requisicao FOREIGN KEY (requisicao_id) REFERENCES tb_requisicoes(id),
    CONSTRAINT fk_requisicao_itens_material FOREIGN KEY (material_id) REFERENCES tb_materiais(id)
);

CREATE INDEX idx_requisicoes_gerente ON tb_requisicoes(gerente_solicitante_id, criada_em DESC);
CREATE INDEX idx_requisicoes_encarregado ON tb_requisicoes(encarregado_destinatario_id, status, criada_em DESC);
