CREATE TABLE tb_solicitacoes_retirada (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operador_responsavel_id BIGINT NOT NULL,
    encarregado_assinante_id BIGINT NOT NULL,
    contrato_id BIGINT,
    status VARCHAR(30) NOT NULL,
    observacao VARCHAR(1000),
    criada_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    confirmada_em TIMESTAMP(6) WITHOUT TIME ZONE,
    cancelada_em TIMESTAMP(6) WITHOUT TIME ZONE,
    idempotency_key VARCHAR(100),
    request_fingerprint VARCHAR(64),
    CONSTRAINT ck_solicitacoes_retirada_status
        CHECK (status IN ('AGUARDANDO_ASSINATURA', 'CONFIRMADA', 'CANCELADA')),
    CONSTRAINT fk_solicitacoes_retirada_operador
        FOREIGN KEY (operador_responsavel_id) REFERENCES tb_usuarios(id),
    CONSTRAINT fk_solicitacoes_retirada_encarregado
        FOREIGN KEY (encarregado_assinante_id) REFERENCES tb_usuarios(id),
    CONSTRAINT fk_solicitacoes_retirada_contrato
        FOREIGN KEY (contrato_id) REFERENCES tb_contratos(id),
    CONSTRAINT uk_solicitacoes_retirada_operador_idempotency
        UNIQUE (operador_responsavel_id, idempotency_key)
);

CREATE INDEX idx_solicitacoes_retirada_encarregado_status
    ON tb_solicitacoes_retirada(encarregado_assinante_id, status, criada_em DESC);

CREATE INDEX idx_solicitacoes_retirada_operador_status
    ON tb_solicitacoes_retirada(operador_responsavel_id, status, criada_em DESC);

CREATE TABLE tb_solicitacoes_retirada_itens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitacao_retirada_id BIGINT NOT NULL,
    material_id BIGINT NOT NULL,
    quantidade INTEGER NOT NULL,
    CONSTRAINT ck_solicitacoes_retirada_itens_quantidade CHECK (quantidade > 0),
    CONSTRAINT fk_solicitacoes_retirada_itens_solicitacao
        FOREIGN KEY (solicitacao_retirada_id) REFERENCES tb_solicitacoes_retirada(id),
    CONSTRAINT fk_solicitacoes_retirada_itens_material
        FOREIGN KEY (material_id) REFERENCES tb_materiais(id),
    CONSTRAINT uk_solicitacoes_retirada_itens_material
        UNIQUE (solicitacao_retirada_id, material_id)
);

CREATE INDEX idx_solicitacoes_retirada_itens_material
    ON tb_solicitacoes_retirada_itens(material_id);
