CREATE TABLE tb_assinaturas_retirada (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitacao_retirada_id BIGINT NOT NULL,
    encarregado_assinante_id BIGINT NOT NULL,
    data_assinatura TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    storage_key VARCHAR(500) NOT NULL,
    nome_arquivo_original VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    tamanho_bytes BIGINT NOT NULL,
    sha256 VARCHAR(64) NOT NULL,
    CONSTRAINT ck_assinaturas_retirada_tamanho CHECK (tamanho_bytes > 0),
    CONSTRAINT uk_assinaturas_retirada_solicitacao UNIQUE (solicitacao_retirada_id),
    CONSTRAINT fk_assinaturas_retirada_solicitacao
        FOREIGN KEY (solicitacao_retirada_id) REFERENCES tb_solicitacoes_retirada(id),
    CONSTRAINT fk_assinaturas_retirada_encarregado
        FOREIGN KEY (encarregado_assinante_id) REFERENCES tb_usuarios(id)
);

ALTER TABLE tb_movimentacoes
    ADD COLUMN encarregado_assinante_id BIGINT;

ALTER TABLE tb_movimentacoes
    ADD CONSTRAINT fk_movimentacoes_encarregado_assinante
        FOREIGN KEY (encarregado_assinante_id) REFERENCES tb_usuarios(id);

ALTER TABLE tb_movimentacoes
    ADD COLUMN solicitacao_retirada_id BIGINT;

ALTER TABLE tb_movimentacoes
    ADD CONSTRAINT fk_movimentacoes_solicitacao_retirada
        FOREIGN KEY (solicitacao_retirada_id) REFERENCES tb_solicitacoes_retirada(id);

CREATE INDEX idx_movimentacoes_encarregado_assinante
    ON tb_movimentacoes(encarregado_assinante_id);

CREATE INDEX idx_movimentacoes_solicitacao_retirada
    ON tb_movimentacoes(solicitacao_retirada_id);

ALTER TABLE tb_movimentacoes
    ADD CONSTRAINT uk_movimentacoes_solicitacao_material
        UNIQUE (solicitacao_retirada_id, material_id);

ALTER TABLE tb_comprovantes_movimentacao
    ADD COLUMN solicitacao_retirada_id BIGINT;

ALTER TABLE tb_comprovantes_movimentacao
    ADD COLUMN operador_responsavel_id BIGINT;

ALTER TABLE tb_comprovantes_movimentacao
    ADD COLUMN operador_responsavel_nome VARCHAR(150);

ALTER TABLE tb_comprovantes_movimentacao
    ADD COLUMN encarregado_assinante_id BIGINT;

ALTER TABLE tb_comprovantes_movimentacao
    ADD COLUMN encarregado_assinante_nome VARCHAR(150);

CREATE OR REPLACE FUNCTION fn_bloquear_alteracao_movimentacao_finalizada()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.quantidade IS DISTINCT FROM NEW.quantidade
        OR OLD.tipo IS DISTINCT FROM NEW.tipo
        OR OLD.data_movimentacao IS DISTINCT FROM NEW.data_movimentacao
        OR OLD.data_finalizacao IS DISTINCT FROM NEW.data_finalizacao
        OR OLD.observacao IS DISTINCT FROM NEW.observacao
        OR OLD.funcionario_id IS DISTINCT FROM NEW.funcionario_id
        OR OLD.contrato_id IS DISTINCT FROM NEW.contrato_id
        OR OLD.material_id IS DISTINCT FROM NEW.material_id
        OR OLD.usuario_id IS DISTINCT FROM NEW.usuario_id
        OR OLD.nota_fiscal_id IS DISTINCT FROM NEW.nota_fiscal_id
        OR OLD.idempotency_key IS DISTINCT FROM NEW.idempotency_key
        OR OLD.request_fingerprint IS DISTINCT FROM NEW.request_fingerprint
        OR OLD.movimentacao_origem_id IS DISTINCT FROM NEW.movimentacao_origem_id
        OR OLD.encarregado_assinante_id IS DISTINCT FROM NEW.encarregado_assinante_id
        OR OLD.solicitacao_retirada_id IS DISTINCT FROM NEW.solicitacao_retirada_id
    THEN
        RAISE EXCEPTION 'Movimentacao finalizada nao pode ser alterada';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
