CREATE TABLE tb_funcionarios (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 nome VARCHAR(150) NOT NULL,
                                 cpf VARCHAR(20) NOT NULL,
                                 cargo VARCHAR(100) NOT NULL,
                                 ativo BOOLEAN NOT NULL DEFAULT TRUE,

                                 CONSTRAINT uk_funcionarios_cpf UNIQUE (cpf)
);


CREATE TABLE tb_contratos (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              nome VARCHAR(150) NOT NULL,
                              descricao VARCHAR(500),
                              ativo BOOLEAN NOT NULL DEFAULT TRUE
);


CREATE TABLE tb_materiais (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              nome VARCHAR(150) NOT NULL,
                              descricao VARCHAR(500),
                              quantidade_estoque INTEGER NOT NULL DEFAULT 0,

                              CONSTRAINT ck_materiais_estoque
                                  CHECK (quantidade_estoque >= 0)
);


CREATE TABLE tb_movimentacoes (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                  funcionario_id BIGINT,
                                  contrato_id BIGINT,
                                  material_id BIGINT NOT NULL,

                                  quantidade INTEGER NOT NULL,
                                  tipo VARCHAR(20) NOT NULL,
                                  data_movimentacao TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,

                                  CONSTRAINT ck_movimentacoes_quantidade
                                      CHECK (quantidade > 0),

                                  CONSTRAINT ck_movimentacoes_tipo
                                      CHECK (
                                          tipo IN (
                                                   'ENTRADA',
                                                   'RETIRADA',
                                                   'DEVOLUCAO'
                                              )
                                          ),

                                  CONSTRAINT fk_movimentacoes_funcionario
                                      FOREIGN KEY (funcionario_id)
                                          REFERENCES tb_funcionarios(id),

                                  CONSTRAINT fk_movimentacoes_contrato
                                      FOREIGN KEY (contrato_id)
                                          REFERENCES tb_contratos(id),

                                  CONSTRAINT fk_movimentacoes_material
                                      FOREIGN KEY (material_id)
                                          REFERENCES tb_materiais(id)
);


CREATE INDEX idx_movimentacoes_funcionario
    ON tb_movimentacoes(funcionario_id);

CREATE INDEX idx_movimentacoes_contrato
    ON tb_movimentacoes(contrato_id);

CREATE INDEX idx_movimentacoes_material
    ON tb_movimentacoes(material_id);

CREATE INDEX idx_movimentacoes_data
    ON tb_movimentacoes(data_movimentacao);