CREATE TABLE tb_usuarios (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                             username VARCHAR(100) NOT NULL,
                             senha VARCHAR(255) NOT NULL,
                             role VARCHAR(20) NOT NULL,
                             ativo BOOLEAN NOT NULL DEFAULT TRUE,

                             CONSTRAINT ck_usuarios_username_nao_vazio
                                 CHECK (BTRIM(username) <> ''),

                             CONSTRAINT ck_usuarios_senha_nao_vazia
                                 CHECK (BTRIM(senha) <> ''),

                             CONSTRAINT ck_usuarios_role
                                 CHECK (role IN ('ADMIN', 'OPERADOR', 'CONSULTA'))
);


-- Impede usuários iguais com diferenças de maiúsculas,
-- minúsculas ou espaços nas extremidades.
CREATE UNIQUE INDEX uk_usuarios_username_normalizado
    ON tb_usuarios (LOWER(BTRIM(username)));


-- A quantidade de qualquer movimentação deve estar
-- entre 1 e 10.000.
ALTER TABLE tb_movimentacoes
    ADD CONSTRAINT ck_movimentacoes_quantidade_valida
        CHECK (quantidade BETWEEN 1 AND 10000);


-- O estoque total nunca pode ficar negativo.
ALTER TABLE tb_materiais
    ADD CONSTRAINT ck_materiais_estoque_nao_negativo
        CHECK (quantidade_estoque >= 0);


-- Materiais não podem possuir o mesmo nome,
-- ignorando maiúsculas, minúsculas e espaços externos.
CREATE UNIQUE INDEX uk_materiais_nome_normalizado
    ON tb_materiais (LOWER(BTRIM(nome)));


-- Contratos não podem possuir o mesmo nome,
-- ignorando maiúsculas, minúsculas e espaços externos.
CREATE UNIQUE INDEX uk_contratos_nome_normalizado
    ON tb_contratos (LOWER(BTRIM(nome)));


-- Considera iguais CPFs formatados e não formatados.
-- Exemplo:
-- 529.982.247-25
-- 52998224725
CREATE UNIQUE INDEX uk_funcionarios_cpf_normalizado
    ON tb_funcionarios (
                        REGEXP_REPLACE(cpf, '[^0-9]', '', 'g')
        );


-- O PostgreSQL garante que existam exatamente 11 números.
-- A validação dos dígitos verificadores continua sendo feita
-- no Java por meio de @CPF.
ALTER TABLE tb_funcionarios
    ADD CONSTRAINT ck_funcionarios_cpf_11_digitos
        CHECK (
            LENGTH(REGEXP_REPLACE(cpf, '[^0-9]', '', 'g')) = 11
            );