CREATE TABLE tb_notas_fiscais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero VARCHAR(50) NOT NULL,
    serie VARCHAR(20) NOT NULL,
    chave_acesso VARCHAR(44) NOT NULL,
    fornecedor VARCHAR(200) NOT NULL,
    cnpj_fornecedor VARCHAR(14) NOT NULL,
    data_emissao DATE NOT NULL,
    data_entrada TIMESTAMP(6) WITHOUT TIME ZONE,
    status VARCHAR(20) NOT NULL,
    cadastrada_por_id BIGINT NOT NULL,
    data_cadastro TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    caminho_arquivo VARCHAR(1000),

    CONSTRAINT uk_notas_fiscais_chave_acesso UNIQUE (chave_acesso),
    CONSTRAINT ck_notas_fiscais_numero_nao_vazio
        CHECK (BTRIM(numero) <> ''),
    CONSTRAINT ck_notas_fiscais_serie_nao_vazia
        CHECK (BTRIM(serie) <> ''),
    CONSTRAINT ck_notas_fiscais_fornecedor_nao_vazio
        CHECK (BTRIM(fornecedor) <> ''),
    CONSTRAINT ck_notas_fiscais_chave_acesso
        CHECK (chave_acesso ~ '^[0-9]{44}$'),
    CONSTRAINT ck_notas_fiscais_cnpj_fornecedor
        CHECK (cnpj_fornecedor ~ '^[0-9]{14}$'),
    CONSTRAINT ck_notas_fiscais_status
        CHECK (status IN ('RASCUNHO', 'CONFIRMADA')),
    CONSTRAINT fk_notas_fiscais_usuario
        FOREIGN KEY (cadastrada_por_id)
            REFERENCES tb_usuarios(id)
);

CREATE TABLE tb_itens_nota_fiscal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nota_fiscal_id BIGINT NOT NULL,
    material_id BIGINT NOT NULL,
    quantidade INTEGER NOT NULL,
    valor_unitario NUMERIC(19, 2) NOT NULL,

    CONSTRAINT ck_itens_nota_fiscal_quantidade
        CHECK (quantidade BETWEEN 1 AND 10000),
    CONSTRAINT ck_itens_nota_fiscal_valor_unitario
        CHECK (valor_unitario >= 0),
    CONSTRAINT fk_itens_nota_fiscal_nota
        FOREIGN KEY (nota_fiscal_id)
            REFERENCES tb_notas_fiscais(id),
    CONSTRAINT fk_itens_nota_fiscal_material
        FOREIGN KEY (material_id)
            REFERENCES tb_materiais(id)
);

CREATE INDEX idx_notas_fiscais_status
    ON tb_notas_fiscais(status);

CREATE INDEX idx_notas_fiscais_data_emissao
    ON tb_notas_fiscais(data_emissao);

CREATE INDEX idx_itens_nota_fiscal_nota
    ON tb_itens_nota_fiscal(nota_fiscal_id);

CREATE INDEX idx_itens_nota_fiscal_material
    ON tb_itens_nota_fiscal(material_id);

ALTER TABLE tb_movimentacoes
    ADD COLUMN nota_fiscal_id BIGINT;

ALTER TABLE tb_movimentacoes
    ADD CONSTRAINT fk_movimentacoes_nota_fiscal
        FOREIGN KEY (nota_fiscal_id)
            REFERENCES tb_notas_fiscais(id);

CREATE INDEX idx_movimentacoes_nota_fiscal
    ON tb_movimentacoes(nota_fiscal_id);
