ALTER TABLE tb_movimentacoes
    ADD COLUMN observacao VARCHAR(1000);

ALTER TABLE tb_movimentacoes
    ADD COLUMN data_finalizacao TIMESTAMP(6) WITHOUT TIME ZONE;

UPDATE tb_movimentacoes
SET data_finalizacao = data_movimentacao
WHERE data_finalizacao IS NULL;

ALTER TABLE tb_movimentacoes
    ALTER COLUMN data_finalizacao SET NOT NULL;

CREATE TABLE tb_comprovantes_movimentacao (
    movimentacao_id BIGINT PRIMARY KEY,
    tipo VARCHAR(20) NOT NULL,
    quantidade INTEGER NOT NULL,
    data_movimentacao TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    data_finalizacao TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    observacao VARCHAR(1000),

    material_id BIGINT NOT NULL,
    material_nome VARCHAR(150) NOT NULL,
    material_descricao VARCHAR(500),

    funcionario_id BIGINT,
    funcionario_nome VARCHAR(150),
    funcionario_cargo VARCHAR(100),

    contrato_id BIGINT,
    contrato_nome VARCHAR(150),
    contrato_descricao VARCHAR(500),

    usuario_id BIGINT,
    usuario_username VARCHAR(100),

    nota_fiscal_id BIGINT,
    nota_fiscal_numero VARCHAR(50),
    nota_fiscal_serie VARCHAR(20),
    nota_fiscal_chave_acesso VARCHAR(44),
    nota_fiscal_fornecedor VARCHAR(200),
    nota_fiscal_cnpj_fornecedor VARCHAR(14),
    nota_fiscal_data_emissao DATE,
    nota_fiscal_data_entrada TIMESTAMP(6) WITHOUT TIME ZONE,

    gerado_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    versao INTEGER NOT NULL,

    CONSTRAINT fk_comprovantes_movimentacao
        FOREIGN KEY (movimentacao_id)
            REFERENCES tb_movimentacoes(id),
    CONSTRAINT ck_comprovantes_tipo
        CHECK (tipo IN ('ENTRADA', 'RETIRADA', 'DEVOLUCAO')),
    CONSTRAINT ck_comprovantes_quantidade
        CHECK (quantidade BETWEEN 1 AND 10000),
    CONSTRAINT ck_comprovantes_versao
        CHECK (versao >= 1)
);

INSERT INTO tb_comprovantes_movimentacao (
    movimentacao_id,
    tipo,
    quantidade,
    data_movimentacao,
    data_finalizacao,
    observacao,
    material_id,
    material_nome,
    material_descricao,
    funcionario_id,
    funcionario_nome,
    funcionario_cargo,
    contrato_id,
    contrato_nome,
    contrato_descricao,
    usuario_id,
    usuario_username,
    nota_fiscal_id,
    nota_fiscal_numero,
    nota_fiscal_serie,
    nota_fiscal_chave_acesso,
    nota_fiscal_fornecedor,
    nota_fiscal_cnpj_fornecedor,
    nota_fiscal_data_emissao,
    nota_fiscal_data_entrada,
    gerado_em,
    versao
)
SELECT
    movimentacao.id,
    movimentacao.tipo,
    movimentacao.quantidade,
    movimentacao.data_movimentacao,
    movimentacao.data_finalizacao,
    movimentacao.observacao,
    material.id,
    material.nome,
    material.descricao,
    funcionario.id,
    funcionario.nome,
    funcionario.cargo,
    contrato.id,
    contrato.nome,
    contrato.descricao,
    usuario.id,
    usuario.username,
    nota.id,
    nota.numero,
    nota.serie,
    nota.chave_acesso,
    nota.fornecedor,
    nota.cnpj_fornecedor,
    nota.data_emissao,
    nota.data_entrada,
    CURRENT_TIMESTAMP,
    1
FROM tb_movimentacoes movimentacao
JOIN tb_materiais material
    ON material.id = movimentacao.material_id
LEFT JOIN tb_funcionarios funcionario
    ON funcionario.id = movimentacao.funcionario_id
LEFT JOIN tb_contratos contrato
    ON contrato.id = movimentacao.contrato_id
LEFT JOIN tb_usuarios usuario
    ON usuario.id = movimentacao.usuario_id
LEFT JOIN tb_notas_fiscais nota
    ON nota.id = movimentacao.nota_fiscal_id;

CREATE TABLE tb_evidencias_movimentacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movimentacao_id BIGINT NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    data_evidencia TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    funcionario_id BIGINT NOT NULL,
    funcionario_nome VARCHAR(150) NOT NULL,
    registrada_por_id BIGINT NOT NULL,
    registrada_por_username VARCHAR(100) NOT NULL,
    storage_key VARCHAR(500) NOT NULL,
    nome_arquivo_original VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    tamanho_bytes BIGINT NOT NULL,
    sha256 VARCHAR(64) NOT NULL,

    CONSTRAINT fk_evidencias_movimentacao
        FOREIGN KEY (movimentacao_id)
            REFERENCES tb_movimentacoes(id),
    CONSTRAINT uk_evidencias_storage_key
        UNIQUE (storage_key),
    CONSTRAINT uk_evidencias_movimentacao_tipo
        UNIQUE (movimentacao_id, tipo),
    CONSTRAINT ck_evidencias_tipo
        CHECK (tipo IN ('ASSINATURA', 'FOTO_DEVOLUCAO')),
    CONSTRAINT ck_evidencias_tamanho
        CHECK (tamanho_bytes > 0),
    CONSTRAINT ck_evidencias_sha256
        CHECK (LENGTH(sha256) = 64)
);

CREATE INDEX idx_evidencias_movimentacao
    ON tb_evidencias_movimentacao(movimentacao_id);
